name: DVC Diff
on:
  push:
    branches:
      - main  # Run the workflow when there is a push to the main branch

jobs:
  dvc-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches so we can check them out later

      - name: List directory contents for debugging
        run: ls -la
        id: list-repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install DVC
        run: pip install dvc

      - name: Checkout and pull data for branch i200503
        run: |
          git checkout i200503
          dvc pull
        id: i200503

      - name: DVC Diff between i200503 and i200707
        run: |
          git checkout i200503
          dvc pull
          git checkout i200707
          dvc pull
          dvc diff i200503 i200707
        id: diff1

      - name: DVC Diff between i200503 and i200822
        run: |
          git checkout i200503
          dvc pull
          git checkout i200822
          dvc pull
          dvc diff i200503 i200822
        id: diff2

      - name: DVC Diff between i200707 and i200822
        run: |
          git checkout i200707
          dvc pull
          git checkout i200822
          dvc pull
          dvc diff i200707 i200822
        id: diff3
