name: DVC Diff

on:
  push:
    branches: [ main ]  # Run the workflow when there is a push to the main branch

jobs:
  dvc-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          # Fetch all branches so we can check them out later
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install DVC
        run: pip install dvc

      - name: Checkout and pull data for all branches
        run: |
          git checkout main
          dvc pull

          git checkout i200503
          dvc pull

          git checkout i200707
          dvc pull

          git checkout i200822
          dvc pull
        id: checkout_and_pull

      - name: DVC Diff between main and other branches
        run: |
          git checkout main
          dvc diff main i200503
          dvc diff main i200707
          dvc diff main i200822
        id: diff_main

      - name: DVC Diff between feature branches
        run: |
          git checkout i200503
          dvc diff i200503 i200707
          dvc diff i200503 i200822

          git checkout i200707
          dvc diff i200707 i200822
        id: diff_features
